baseurl: "" # The subpath of your site. Use "" if you're hosting a blog at the root level.
url: "https://www.buybitcoinworldwide.com" # the base hostname & protocol for your site
title: "Buy Bitcoin Worldwide"
markdown: kramdown
paginate: 10
paginate_path: "/blog/page:num/"
sass:
  sass_dir: _sass
  style: compressed

collections:
  faqs:
    output: true
  kb:
    output: true
  wallets:
    output: true 
  exchanges:
    output: true       

exclude:
  - "README.md"
  - "CHANGELOG.md"
  - "CNAME"
  - "Gemfile"
  - "Gemfile.lock"
permalink: :title
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: "/countries"
      type: "countries"
    values:
      layout: "country"
  -
    scope:
      path: "/pmethods"
      type: "pmethod"
    values:
      layout: "help"
  -
    scope:
      path: "/indexes"
      type: "index"
    values:
      layout: "home"
  -
    scope:
      path: "/redirects"
      type: "redirect"
    values:
      layout: "redirect"